Llama3-Instruct_armorm_rainbowpo_epoch_ablation_epoch4:
  completions_kwargs:
    batch_size: 400
    # do_sample: true
    max_new_tokens: 4096
    model_kwargs:
      dtype: bfloat16
    model_name: /home/hanyang/RainbowPO/models_rlhf/Llama3-Instruct_armorm_rainbowpo_beta_10_hadv_0.1_mixing_0.25_retrain/checkpoint-950
    stop_token_ids:
    - 128001
    - 128009
    temperature: 0.7
    top_p: 0.9
    # presence_penalty: 0.1
    # frequency_penalty: 0.1
    seed: 42
  fn_completions: vllm_local_completions
  pretty_name: Llama3-Instruct_armorm_rainbowpo_epoch_ablation_epoch4
  prompt_template: Llama-3-Instruct-8B-RainbowPO/prompt.txt