Llama-3-Instruct-8B-DPO-beta=0.01-lr=0.3:
  completions_kwargs:
    batch_size: 400
    # do_sample: true
    max_new_tokens: 2048
    model_kwargs:
      dtype: bfloat16
    model_name: <somepath>/trl/models_rlhf/learning_rate/Llama3-Instruct_armorm_dpo_beta_0.01_lr_0.3
    stop_token_ids:
    - 128001
    - 128009
    temperature: 0.7
    top_p: 1.0
    seed: 42
  fn_completions: vllm_local_completions
  pretty_name: Llama-3-Instruct-8B-DPO-beta=0.01-lr=0.3
  prompt_template: Llama-3-Instruct-8B-RainbowPO/prompt.txt